from __future__ import annotations

import faulthandler
import os
import queue
import re
import threading
import time
import tkinter as tk
import webbrowser
import zipfile
from pathlib import Path
from urllib.parse import urlsplit
from tkinter import filedialog, messagebox, simpledialog, ttk

from ...archive.facade import *
from ...browser.facade import *
from ...chat import ChatEvent, ChatState, ChatWatchManager
from ...commands.facade import *
from ...config import config_path, save_config
from ...domain import AppConfig, CommandSpec, Project, UrlGroup, UrlSpec
from ...platform.windows.desktop import open_folder, open_in_vscode
from ..constants import *
from ..dialogs.command import CommandDialog
from ..dialogs.url import UrlDialog
from ..dialogs.misc import MultiSelectDialog, SnapshotDiffDialog
from ..widgets import ScrollableFrame

class ProjectSettingsController:
    def _path_row(self, parent: ttk.Frame, row: int, label: str, var: tk.StringVar, browse: bool):
        ttk.Label(parent, text=label).grid(row=row, column=0, sticky="w", padx=(0, 8), pady=4)
        ttk.Entry(parent, textvariable=var).grid(row=row, column=1, sticky="ew", pady=4)
        if browse:
            ttk.Button(parent, text="Browse…", command=lambda v=var: self._browse_dir(v)).grid(
                row=row, column=2, padx=(8, 0), pady=4
            )

    def _toggle_project_settings(self):
        self._project_settings_visible = not self._project_settings_visible
        if self._project_settings_visible:
            self.project_settings_frame.pack(fill="x", padx=4, pady=(0, 10), after=self.project_settings_toggle)
            self.project_settings_toggle.configure(text="▼ Project Settings")
        else:
            self.project_settings_frame.pack_forget()
            self.project_settings_toggle.configure(text="▶ Project Settings")

    def _bind_project_settings_autosave(self):
        vars_to_watch = [
            self.name_var,
            self.match_var,
            self.downloads_var,
            self.extract_parent_var,
            self.repo_root_var,
            self.delete_old_var,
            self.preserve_extract_git_var,
            self.confirm_extract_var,
            self.auto_extract_var,
            self.auto_stop_commands_before_extract_var,
            self.preserve_replace_git_var,
            self.zip_exclude_git_var,
        ]
        for var in vars_to_watch:
            var.trace_add("write", self._on_project_setting_changed)
        self.exclusions_text.bind("<<Modified>>", self._on_exclusions_modified, add=True)
        self.exclusions_text.edit_modified(False)

    def _on_project_setting_changed(self, *_args):
        if self._loading_form or self._closing:
            return
        self._schedule_project_autosave()

    def _on_auto_extract_setting_changed(self):
        """Persist the Project Settings toggle and act on an already-ready ZIP."""
        if self._loading_form or self._closing:
            return
        project = self._current_project()
        if project is not None:
            project.auto_extract_when_ready = bool(self.auto_extract_var.get())
            self._save_config()
        self._schedule_project_autosave()
        if self.auto_extract_var.get():
            self.after_idle(self._maybe_auto_extract_ready_project)

    def _on_exclusions_modified(self, _event=None):
        try:
            modified = bool(self.exclusions_text.edit_modified())
            self.exclusions_text.edit_modified(False)
        except tk.TclError:
            return
        if modified and not self._loading_form and not self._closing:
            self._schedule_project_autosave()

    def _schedule_project_autosave(self):
        # ``after_idle`` is effectively immediate to the user while coalescing
        # the multiple Tk variable notifications generated by one UI action.
        # Keeping one scheduled callback also prevents a backlog during typing.
        if self._autosave_after_id is not None:
            return
        try:
            self._autosave_after_id = self.after_idle(self._autosave_project_settings_now)
        except tk.TclError:
            self._autosave_after_id = None

    def _autosave_project_settings_now(self):
        self._autosave_after_id = None
        if self._closing or self._loading_form:
            return
        project = self._current_project()
        if project is None:
            return
        # Empty name/match values are not committed because the rest of the app
        # requires them, but every valid edit is persisted without a Save button.
        if not self.name_var.get().strip() or not self.match_var.get().strip():
            return
        if self._commit_form_to_project():
            self._save_config()
            self._update_project_status_cells()
            self._update_download_status_label()

    def _current_index(self) -> int | None:
        selected = self.project_list.selection()
        if not selected:
            return None
        project_id = selected[0]
        for index, project in enumerate(self.config_data.projects):
            if project.project_id == project_id:
                return index
        return None

    def _current_project(self) -> Project | None:
        index = self._current_index()
        if index is None or index >= len(self.config_data.projects):
            return None
        return self.config_data.projects[index]

    def _project_at(self, index: int | None) -> Project | None:
        if index is None or index < 0 or index >= len(self.config_data.projects):
            return None
        return self.config_data.projects[index]

    def _project_by_id(self, project_id: str) -> Project | None:
        return next((project for project in self.config_data.projects if project.project_id == project_id), None)

    def _on_project_select(self, _event=None):
        if self._loading_form:
            return
        index = self._current_index()
        if index is None:
            return
        self._acknowledge_project_attention(self._project_at(index))
        if self._loaded_project_index is not None and self._loaded_project_index != index:
            self._commit_form_to_project(self._loaded_project_index)
        self.config_data.selected_project = index
        self._load_project_form()
        self._load_files_project(self._project_at(index))
        self._refresh_commands()
        self._refresh_urls()
        self._refresh_prompts()
        self._refresh_notes()
        self._update_download_chatgpt_button()
        self._update_paste_prompt_button()
        self._update_paste_note_button()
        self._save_config()
        # Project selection should immediately reconcile already-open browser
        # windows. The forced pass enables the passive UIA fallback rather than
        # waiting for the normal MSAA-only periodic scan.
        self._request_browser_reconcile()

    def _clear_project_form(self):
        self._loading_form = True
        try:
            for var in [self.name_var, self.match_var, self.downloads_var, self.extract_parent_var, self.repo_root_var]:
                var.set("")
            for var in [self.delete_old_var, self.auto_stop_commands_before_extract_var, self.preserve_extract_git_var, self.preserve_replace_git_var, self.zip_exclude_git_var]:
                var.set(False)
            self.confirm_extract_var.set(True)
            self.auto_extract_var.set(False)
            self.exclusions_text.delete("1.0", "end")
            self.exclusions_text.edit_modified(False)
            self.snapshot_status_var.set("No project selected")
            self.last_extracted_var.set("Last extracted: none")
            if hasattr(self, "download_status_var"):
                self.download_status_var.set("")
            if hasattr(self, "chat_worked_for_var"):
                self.chat_worked_for_var.set("ChatGPT worked for: —")
            self._loaded_project_index = None
        finally:
            self._loading_form = False
        if hasattr(self, "files_tree"):
            self._load_files_project(None)

    def _load_project_form(self):
        project = self._current_project()
        if not project:
            self._clear_project_form()
            return
        selected_index = self._current_index()
        self._loading_form = True
        try:
            self.name_var.set(project.name)
            self.match_var.set(project.match_string)
            self.downloads_var.set(project.downloads_dir)
            self.extract_parent_var.set(project.extract_parent)
            self.repo_root_var.set(project.repo_root)
            self.delete_old_var.set(project.delete_older_zips)
            self.preserve_extract_git_var.set(project.preserve_git_on_extract)
            self.confirm_extract_var.set(project.confirm_extract_newest)
            self.auto_extract_var.set(project.auto_extract_when_ready)
            self.auto_stop_commands_before_extract_var.set(project.auto_stop_commands_before_extract)
            self.preserve_replace_git_var.set(project.preserve_git_on_replace)
            self.zip_exclude_git_var.set(project.zip_exclude_git)
            self.exclusions_text.delete("1.0", "end")
            self.exclusions_text.insert("1.0", "\n".join(project.excluded_dirs))
            self.exclusions_text.edit_modified(False)
            self.snapshot_status_var.set(
                f"Snapshot: {len(project.snapshot):,} entries" if project.snapshot else "Snapshot: not set"
            )
            self.last_extracted_var.set(self._last_extracted_label(project.last_extracted_zip))
            self._loaded_project_index = selected_index
        finally:
            self._loading_form = False
        self._update_download_status_label()
        self._update_project_chat_timing_label()

    def _commit_form_to_project(self, index: int | None = None) -> bool:
        project = self._project_at(self._loaded_project_index if index is None else index)
        if not project or self._loading_form:
            return False
        name = self.name_var.get().strip()
        match = self.match_var.get().strip()
        if not name or not match:
            return False
        project.name = name
        project.match_string = match
        project.downloads_dir = self.downloads_var.get().strip()
        project.extract_parent = self.extract_parent_var.get().strip()
        project.repo_root = self.repo_root_var.get().strip()
        project.delete_older_zips = self.delete_old_var.get()
        project.preserve_git_on_extract = self.preserve_extract_git_var.get()
        project.confirm_extract_newest = self.confirm_extract_var.get()
        project.auto_extract_when_ready = self.auto_extract_var.get()
        project.auto_stop_commands_before_extract = self.auto_stop_commands_before_extract_var.get()
        project.preserve_git_on_replace = self.preserve_replace_git_var.get()
        project.zip_exclude_git = self.zip_exclude_git_var.get()
        project.excluded_dirs = [line.strip() for line in self.exclusions_text.get("1.0", "end").splitlines() if line.strip()]
        return True

    def _browse_dir(self, var: tk.StringVar):
        initial = var.get().strip()
        path = filedialog.askdirectory(parent=self, initialdir=initial if initial else None)
        if path:
            var.set(path)

    def _validate_project_settings(self) -> Project | None:
        project = self._current_project()
        if not project:
            messagebox.showinfo("No project", "Add or select a project first.", parent=self)
            return None
        if not self.name_var.get().strip() or not self.match_var.get().strip():
            messagebox.showerror("Missing required setting", "Project name and ZIP match string are required.", parent=self)
            return None
        self._commit_form_to_project()
        self._save_config()
        return project

